version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    command: "npm run dev"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    ports:
      - "4000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - ROLLUP_NO_NATIVE=true
    command: "npm run dev"
